package TestDataManager;

import com.github.javafaker.Faker;
import mapbox.pojos.DatasetRequest;
import mapbox.pojos.Feature;
import mapbox.pojos.Geometry;

import java.util.HashMap;
import java.util.Map;

public class DataSeeder {
    private static final Faker faker = new Faker();

    public static DatasetRequest seedDataset() {
        return DatasetRequest.builder()
                .name("Dataset " + faker.number().digits(4))
                .description("Generated by DataSeeder")
                .build();
    }

    public static Feature seedFeature(String featureId) {
        Map<String, Object> props = new HashMap<>();
        props.put("name", faker.address().cityName());

        return Feature.builder()
                .id(featureId)
                .type("Feature")
                .geometry(Geometry.builder()
                        .type("Point")
                        .coordinates(java.util.Arrays.asList(
                                Double.parseDouble(faker.address().longitude()),
                                Double.parseDouble(faker.address().latitude())
                        ))
                        .build())
                .properties(props)
                .build();
    }
}
