image: node:20

stages:
  - test

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - ~/.cache/ms-playwright/

playwright_tests:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npx playwright install --with-deps
  script:
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 30 days

