name: Perf CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Perf/**'
      - '.github/workflows/perf-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Perf/**'
      - '.github/workflows/perf-ci.yml'

jobs:
  load-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Perf
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Node and Build
        run: |
          npm ci
          npm run build
          
      - name: Run k6 load test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: Perf/dist/homepage.spec.bundle.js
          flags: -e TARGET_ENV=qa -e WORKLOAD=load

      - name: Upload k6 html report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: perf-html-report
          path: Perf/html-report.html
          retention-days: 7

      - name: Send Slack Notification (Mock)
        if: always()
        run: echo "Mocking Slack Notification... Status is ${{ job.status }}"
